// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blickfeld/config/algorithm.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_blickfeld_2fconfig_2falgorithm_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_blickfeld_2fconfig_2falgorithm_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "blickfeld/options.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_blickfeld_2fconfig_2falgorithm_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_blickfeld_2fconfig_2falgorithm_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto;
namespace blickfeld {
namespace protocol {
namespace config {
class Algorithm;
class AlgorithmDefaultTypeInternal;
extern AlgorithmDefaultTypeInternal _Algorithm_default_instance_;
class Algorithm_BackgroundSubtraction;
class Algorithm_BackgroundSubtractionDefaultTypeInternal;
extern Algorithm_BackgroundSubtractionDefaultTypeInternal _Algorithm_BackgroundSubtraction_default_instance_;
class Algorithm_NeighborFilter;
class Algorithm_NeighborFilterDefaultTypeInternal;
extern Algorithm_NeighborFilterDefaultTypeInternal _Algorithm_NeighborFilter_default_instance_;
class Algorithm_StaticTransformation;
class Algorithm_StaticTransformationDefaultTypeInternal;
extern Algorithm_StaticTransformationDefaultTypeInternal _Algorithm_StaticTransformation_default_instance_;
}  // namespace config
}  // namespace protocol
}  // namespace blickfeld
PROTOBUF_NAMESPACE_OPEN
template<> ::blickfeld::protocol::config::Algorithm* Arena::CreateMaybeMessage<::blickfeld::protocol::config::Algorithm>(Arena*);
template<> ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* Arena::CreateMaybeMessage<::blickfeld::protocol::config::Algorithm_BackgroundSubtraction>(Arena*);
template<> ::blickfeld::protocol::config::Algorithm_NeighborFilter* Arena::CreateMaybeMessage<::blickfeld::protocol::config::Algorithm_NeighborFilter>(Arena*);
template<> ::blickfeld::protocol::config::Algorithm_StaticTransformation* Arena::CreateMaybeMessage<::blickfeld::protocol::config::Algorithm_StaticTransformation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace blickfeld {
namespace protocol {
namespace config {

// ===================================================================

class Algorithm_BackgroundSubtraction PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blickfeld.protocol.config.Algorithm.BackgroundSubtraction) */ {
 public:
  inline Algorithm_BackgroundSubtraction() : Algorithm_BackgroundSubtraction(nullptr) {};
  virtual ~Algorithm_BackgroundSubtraction();

  Algorithm_BackgroundSubtraction(const Algorithm_BackgroundSubtraction& from);
  Algorithm_BackgroundSubtraction(Algorithm_BackgroundSubtraction&& from) noexcept
    : Algorithm_BackgroundSubtraction() {
    *this = ::std::move(from);
  }

  inline Algorithm_BackgroundSubtraction& operator=(const Algorithm_BackgroundSubtraction& from) {
    CopyFrom(from);
    return *this;
  }
  inline Algorithm_BackgroundSubtraction& operator=(Algorithm_BackgroundSubtraction&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Algorithm_BackgroundSubtraction& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Algorithm_BackgroundSubtraction* internal_default_instance() {
    return reinterpret_cast<const Algorithm_BackgroundSubtraction*>(
               &_Algorithm_BackgroundSubtraction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Algorithm_BackgroundSubtraction& a, Algorithm_BackgroundSubtraction& b) {
    a.Swap(&b);
  }
  inline void Swap(Algorithm_BackgroundSubtraction* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Algorithm_BackgroundSubtraction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Algorithm_BackgroundSubtraction* New() const final {
    return CreateMaybeMessage<Algorithm_BackgroundSubtraction>(nullptr);
  }

  Algorithm_BackgroundSubtraction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Algorithm_BackgroundSubtraction>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Algorithm_BackgroundSubtraction& from);
  void MergeFrom(const Algorithm_BackgroundSubtraction& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Algorithm_BackgroundSubtraction* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blickfeld.protocol.config.Algorithm.BackgroundSubtraction";
  }
  protected:
  explicit Algorithm_BackgroundSubtraction(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto);
    return ::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInitializationFramesFieldNumber = 1,
    kExponentialDecayRateFieldNumber = 2,
  };
  // optional uint32 initialization_frames = 1 [default = 10, (.blickfeld.protocol.d_min) = 1, (.blickfeld.protocol.d_max) = 10];
  bool has_initialization_frames() const;
  private:
  bool _internal_has_initialization_frames() const;
  public:
  void clear_initialization_frames();
  ::PROTOBUF_NAMESPACE_ID::uint32 initialization_frames() const;
  void set_initialization_frames(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_initialization_frames() const;
  void _internal_set_initialization_frames(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional float exponential_decay_rate = 2 [default = 0.0025, (.blickfeld.protocol.d_min) = 0, (.blickfeld.protocol.d_max) = 1];
  bool has_exponential_decay_rate() const;
  private:
  bool _internal_has_exponential_decay_rate() const;
  public:
  void clear_exponential_decay_rate();
  float exponential_decay_rate() const;
  void set_exponential_decay_rate(float value);
  private:
  float _internal_exponential_decay_rate() const;
  void _internal_set_exponential_decay_rate(float value);
  public:

  // @@protoc_insertion_point(class_scope:blickfeld.protocol.config.Algorithm.BackgroundSubtraction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 initialization_frames_;
  float exponential_decay_rate_;
  friend struct ::TableStruct_blickfeld_2fconfig_2falgorithm_2eproto;
};
// -------------------------------------------------------------------

class Algorithm_NeighborFilter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blickfeld.protocol.config.Algorithm.NeighborFilter) */ {
 public:
  inline Algorithm_NeighborFilter() : Algorithm_NeighborFilter(nullptr) {};
  virtual ~Algorithm_NeighborFilter();

  Algorithm_NeighborFilter(const Algorithm_NeighborFilter& from);
  Algorithm_NeighborFilter(Algorithm_NeighborFilter&& from) noexcept
    : Algorithm_NeighborFilter() {
    *this = ::std::move(from);
  }

  inline Algorithm_NeighborFilter& operator=(const Algorithm_NeighborFilter& from) {
    CopyFrom(from);
    return *this;
  }
  inline Algorithm_NeighborFilter& operator=(Algorithm_NeighborFilter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Algorithm_NeighborFilter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Algorithm_NeighborFilter* internal_default_instance() {
    return reinterpret_cast<const Algorithm_NeighborFilter*>(
               &_Algorithm_NeighborFilter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Algorithm_NeighborFilter& a, Algorithm_NeighborFilter& b) {
    a.Swap(&b);
  }
  inline void Swap(Algorithm_NeighborFilter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Algorithm_NeighborFilter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Algorithm_NeighborFilter* New() const final {
    return CreateMaybeMessage<Algorithm_NeighborFilter>(nullptr);
  }

  Algorithm_NeighborFilter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Algorithm_NeighborFilter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Algorithm_NeighborFilter& from);
  void MergeFrom(const Algorithm_NeighborFilter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Algorithm_NeighborFilter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blickfeld.protocol.config.Algorithm.NeighborFilter";
  }
  protected:
  explicit Algorithm_NeighborFilter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto);
    return ::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:blickfeld.protocol.config.Algorithm.NeighborFilter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_blickfeld_2fconfig_2falgorithm_2eproto;
};
// -------------------------------------------------------------------

class Algorithm_StaticTransformation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blickfeld.protocol.config.Algorithm.StaticTransformation) */ {
 public:
  inline Algorithm_StaticTransformation() : Algorithm_StaticTransformation(nullptr) {};
  virtual ~Algorithm_StaticTransformation();

  Algorithm_StaticTransformation(const Algorithm_StaticTransformation& from);
  Algorithm_StaticTransformation(Algorithm_StaticTransformation&& from) noexcept
    : Algorithm_StaticTransformation() {
    *this = ::std::move(from);
  }

  inline Algorithm_StaticTransformation& operator=(const Algorithm_StaticTransformation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Algorithm_StaticTransformation& operator=(Algorithm_StaticTransformation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Algorithm_StaticTransformation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Algorithm_StaticTransformation* internal_default_instance() {
    return reinterpret_cast<const Algorithm_StaticTransformation*>(
               &_Algorithm_StaticTransformation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Algorithm_StaticTransformation& a, Algorithm_StaticTransformation& b) {
    a.Swap(&b);
  }
  inline void Swap(Algorithm_StaticTransformation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Algorithm_StaticTransformation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Algorithm_StaticTransformation* New() const final {
    return CreateMaybeMessage<Algorithm_StaticTransformation>(nullptr);
  }

  Algorithm_StaticTransformation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Algorithm_StaticTransformation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Algorithm_StaticTransformation& from);
  void MergeFrom(const Algorithm_StaticTransformation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Algorithm_StaticTransformation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blickfeld.protocol.config.Algorithm.StaticTransformation";
  }
  protected:
  explicit Algorithm_StaticTransformation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto);
    return ::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRotationMatrixFieldNumber = 1,
    kTranslationVectorFieldNumber = 2,
  };
  // repeated float rotation_matrix = 1 [packed = true, (.blickfeld.protocol.length) = 9, (.blickfeld.protocol.optional) = true];
  int rotation_matrix_size() const;
  private:
  int _internal_rotation_matrix_size() const;
  public:
  void clear_rotation_matrix();
  private:
  float _internal_rotation_matrix(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_rotation_matrix() const;
  void _internal_add_rotation_matrix(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_rotation_matrix();
  public:
  float rotation_matrix(int index) const;
  void set_rotation_matrix(int index, float value);
  void add_rotation_matrix(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      rotation_matrix() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_rotation_matrix();

  // repeated float translation_vector = 2 [packed = true, (.blickfeld.protocol.length) = 3, (.blickfeld.protocol.optional) = true];
  int translation_vector_size() const;
  private:
  int _internal_translation_vector_size() const;
  public:
  void clear_translation_vector();
  private:
  float _internal_translation_vector(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_translation_vector() const;
  void _internal_add_translation_vector(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_translation_vector();
  public:
  float translation_vector(int index) const;
  void set_translation_vector(int index, float value);
  void add_translation_vector(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      translation_vector() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_translation_vector();

  // @@protoc_insertion_point(class_scope:blickfeld.protocol.config.Algorithm.StaticTransformation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > rotation_matrix_;
  mutable std::atomic<int> _rotation_matrix_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > translation_vector_;
  mutable std::atomic<int> _translation_vector_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_blickfeld_2fconfig_2falgorithm_2eproto;
};
// -------------------------------------------------------------------

class Algorithm PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blickfeld.protocol.config.Algorithm) */ {
 public:
  inline Algorithm() : Algorithm(nullptr) {};
  virtual ~Algorithm();

  Algorithm(const Algorithm& from);
  Algorithm(Algorithm&& from) noexcept
    : Algorithm() {
    *this = ::std::move(from);
  }

  inline Algorithm& operator=(const Algorithm& from) {
    CopyFrom(from);
    return *this;
  }
  inline Algorithm& operator=(Algorithm&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Algorithm& default_instance();

  enum AlgoCase {
    kBackgroundSubtraction = 1,
    kNeighborFilter = 2,
    kStaticTransformation = 3,
    ALGO_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Algorithm* internal_default_instance() {
    return reinterpret_cast<const Algorithm*>(
               &_Algorithm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Algorithm& a, Algorithm& b) {
    a.Swap(&b);
  }
  inline void Swap(Algorithm* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Algorithm* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Algorithm* New() const final {
    return CreateMaybeMessage<Algorithm>(nullptr);
  }

  Algorithm* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Algorithm>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Algorithm& from);
  void MergeFrom(const Algorithm& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Algorithm* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blickfeld.protocol.config.Algorithm";
  }
  protected:
  explicit Algorithm(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto);
    return ::descriptor_table_blickfeld_2fconfig_2falgorithm_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Algorithm_BackgroundSubtraction BackgroundSubtraction;
  typedef Algorithm_NeighborFilter NeighborFilter;
  typedef Algorithm_StaticTransformation StaticTransformation;

  // accessors -------------------------------------------------------

  enum : int {
    kBackgroundSubtractionFieldNumber = 1,
    kNeighborFilterFieldNumber = 2,
    kStaticTransformationFieldNumber = 3,
  };
  // .blickfeld.protocol.config.Algorithm.BackgroundSubtraction background_subtraction = 1;
  bool has_background_subtraction() const;
  private:
  bool _internal_has_background_subtraction() const;
  public:
  void clear_background_subtraction();
  const ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction& background_subtraction() const;
  ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* release_background_subtraction();
  ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* mutable_background_subtraction();
  void set_allocated_background_subtraction(::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* background_subtraction);
  private:
  const ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction& _internal_background_subtraction() const;
  ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* _internal_mutable_background_subtraction();
  public:
  void unsafe_arena_set_allocated_background_subtraction(
      ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* background_subtraction);
  ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* unsafe_arena_release_background_subtraction();

  // .blickfeld.protocol.config.Algorithm.NeighborFilter neighbor_filter = 2;
  bool has_neighbor_filter() const;
  private:
  bool _internal_has_neighbor_filter() const;
  public:
  void clear_neighbor_filter();
  const ::blickfeld::protocol::config::Algorithm_NeighborFilter& neighbor_filter() const;
  ::blickfeld::protocol::config::Algorithm_NeighborFilter* release_neighbor_filter();
  ::blickfeld::protocol::config::Algorithm_NeighborFilter* mutable_neighbor_filter();
  void set_allocated_neighbor_filter(::blickfeld::protocol::config::Algorithm_NeighborFilter* neighbor_filter);
  private:
  const ::blickfeld::protocol::config::Algorithm_NeighborFilter& _internal_neighbor_filter() const;
  ::blickfeld::protocol::config::Algorithm_NeighborFilter* _internal_mutable_neighbor_filter();
  public:
  void unsafe_arena_set_allocated_neighbor_filter(
      ::blickfeld::protocol::config::Algorithm_NeighborFilter* neighbor_filter);
  ::blickfeld::protocol::config::Algorithm_NeighborFilter* unsafe_arena_release_neighbor_filter();

  // .blickfeld.protocol.config.Algorithm.StaticTransformation static_transformation = 3;
  bool has_static_transformation() const;
  private:
  bool _internal_has_static_transformation() const;
  public:
  void clear_static_transformation();
  const ::blickfeld::protocol::config::Algorithm_StaticTransformation& static_transformation() const;
  ::blickfeld::protocol::config::Algorithm_StaticTransformation* release_static_transformation();
  ::blickfeld::protocol::config::Algorithm_StaticTransformation* mutable_static_transformation();
  void set_allocated_static_transformation(::blickfeld::protocol::config::Algorithm_StaticTransformation* static_transformation);
  private:
  const ::blickfeld::protocol::config::Algorithm_StaticTransformation& _internal_static_transformation() const;
  ::blickfeld::protocol::config::Algorithm_StaticTransformation* _internal_mutable_static_transformation();
  public:
  void unsafe_arena_set_allocated_static_transformation(
      ::blickfeld::protocol::config::Algorithm_StaticTransformation* static_transformation);
  ::blickfeld::protocol::config::Algorithm_StaticTransformation* unsafe_arena_release_static_transformation();

  void clear_algo();
  AlgoCase algo_case() const;
  // @@protoc_insertion_point(class_scope:blickfeld.protocol.config.Algorithm)
 private:
  class _Internal;
  void set_has_background_subtraction();
  void set_has_neighbor_filter();
  void set_has_static_transformation();

  inline bool has_algo() const;
  inline void clear_has_algo();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union AlgoUnion {
    AlgoUnion() {}
    ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* background_subtraction_;
    ::blickfeld::protocol::config::Algorithm_NeighborFilter* neighbor_filter_;
    ::blickfeld::protocol::config::Algorithm_StaticTransformation* static_transformation_;
  } algo_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_blickfeld_2fconfig_2falgorithm_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Algorithm_BackgroundSubtraction

// optional uint32 initialization_frames = 1 [default = 10, (.blickfeld.protocol.d_min) = 1, (.blickfeld.protocol.d_max) = 10];
inline bool Algorithm_BackgroundSubtraction::_internal_has_initialization_frames() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Algorithm_BackgroundSubtraction::has_initialization_frames() const {
  return _internal_has_initialization_frames();
}
inline void Algorithm_BackgroundSubtraction::clear_initialization_frames() {
  initialization_frames_ = 10u;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Algorithm_BackgroundSubtraction::_internal_initialization_frames() const {
  return initialization_frames_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Algorithm_BackgroundSubtraction::initialization_frames() const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.BackgroundSubtraction.initialization_frames)
  return _internal_initialization_frames();
}
inline void Algorithm_BackgroundSubtraction::_internal_set_initialization_frames(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000001u;
  initialization_frames_ = value;
}
inline void Algorithm_BackgroundSubtraction::set_initialization_frames(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_initialization_frames(value);
  // @@protoc_insertion_point(field_set:blickfeld.protocol.config.Algorithm.BackgroundSubtraction.initialization_frames)
}

// optional float exponential_decay_rate = 2 [default = 0.0025, (.blickfeld.protocol.d_min) = 0, (.blickfeld.protocol.d_max) = 1];
inline bool Algorithm_BackgroundSubtraction::_internal_has_exponential_decay_rate() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Algorithm_BackgroundSubtraction::has_exponential_decay_rate() const {
  return _internal_has_exponential_decay_rate();
}
inline void Algorithm_BackgroundSubtraction::clear_exponential_decay_rate() {
  exponential_decay_rate_ = 0.0025f;
  _has_bits_[0] &= ~0x00000002u;
}
inline float Algorithm_BackgroundSubtraction::_internal_exponential_decay_rate() const {
  return exponential_decay_rate_;
}
inline float Algorithm_BackgroundSubtraction::exponential_decay_rate() const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.BackgroundSubtraction.exponential_decay_rate)
  return _internal_exponential_decay_rate();
}
inline void Algorithm_BackgroundSubtraction::_internal_set_exponential_decay_rate(float value) {
  _has_bits_[0] |= 0x00000002u;
  exponential_decay_rate_ = value;
}
inline void Algorithm_BackgroundSubtraction::set_exponential_decay_rate(float value) {
  _internal_set_exponential_decay_rate(value);
  // @@protoc_insertion_point(field_set:blickfeld.protocol.config.Algorithm.BackgroundSubtraction.exponential_decay_rate)
}

// -------------------------------------------------------------------

// Algorithm_NeighborFilter

// -------------------------------------------------------------------

// Algorithm_StaticTransformation

// repeated float rotation_matrix = 1 [packed = true, (.blickfeld.protocol.length) = 9, (.blickfeld.protocol.optional) = true];
inline int Algorithm_StaticTransformation::_internal_rotation_matrix_size() const {
  return rotation_matrix_.size();
}
inline int Algorithm_StaticTransformation::rotation_matrix_size() const {
  return _internal_rotation_matrix_size();
}
inline void Algorithm_StaticTransformation::clear_rotation_matrix() {
  rotation_matrix_.Clear();
}
inline float Algorithm_StaticTransformation::_internal_rotation_matrix(int index) const {
  return rotation_matrix_.Get(index);
}
inline float Algorithm_StaticTransformation::rotation_matrix(int index) const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.StaticTransformation.rotation_matrix)
  return _internal_rotation_matrix(index);
}
inline void Algorithm_StaticTransformation::set_rotation_matrix(int index, float value) {
  rotation_matrix_.Set(index, value);
  // @@protoc_insertion_point(field_set:blickfeld.protocol.config.Algorithm.StaticTransformation.rotation_matrix)
}
inline void Algorithm_StaticTransformation::_internal_add_rotation_matrix(float value) {
  rotation_matrix_.Add(value);
}
inline void Algorithm_StaticTransformation::add_rotation_matrix(float value) {
  _internal_add_rotation_matrix(value);
  // @@protoc_insertion_point(field_add:blickfeld.protocol.config.Algorithm.StaticTransformation.rotation_matrix)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Algorithm_StaticTransformation::_internal_rotation_matrix() const {
  return rotation_matrix_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Algorithm_StaticTransformation::rotation_matrix() const {
  // @@protoc_insertion_point(field_list:blickfeld.protocol.config.Algorithm.StaticTransformation.rotation_matrix)
  return _internal_rotation_matrix();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Algorithm_StaticTransformation::_internal_mutable_rotation_matrix() {
  return &rotation_matrix_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Algorithm_StaticTransformation::mutable_rotation_matrix() {
  // @@protoc_insertion_point(field_mutable_list:blickfeld.protocol.config.Algorithm.StaticTransformation.rotation_matrix)
  return _internal_mutable_rotation_matrix();
}

// repeated float translation_vector = 2 [packed = true, (.blickfeld.protocol.length) = 3, (.blickfeld.protocol.optional) = true];
inline int Algorithm_StaticTransformation::_internal_translation_vector_size() const {
  return translation_vector_.size();
}
inline int Algorithm_StaticTransformation::translation_vector_size() const {
  return _internal_translation_vector_size();
}
inline void Algorithm_StaticTransformation::clear_translation_vector() {
  translation_vector_.Clear();
}
inline float Algorithm_StaticTransformation::_internal_translation_vector(int index) const {
  return translation_vector_.Get(index);
}
inline float Algorithm_StaticTransformation::translation_vector(int index) const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.StaticTransformation.translation_vector)
  return _internal_translation_vector(index);
}
inline void Algorithm_StaticTransformation::set_translation_vector(int index, float value) {
  translation_vector_.Set(index, value);
  // @@protoc_insertion_point(field_set:blickfeld.protocol.config.Algorithm.StaticTransformation.translation_vector)
}
inline void Algorithm_StaticTransformation::_internal_add_translation_vector(float value) {
  translation_vector_.Add(value);
}
inline void Algorithm_StaticTransformation::add_translation_vector(float value) {
  _internal_add_translation_vector(value);
  // @@protoc_insertion_point(field_add:blickfeld.protocol.config.Algorithm.StaticTransformation.translation_vector)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Algorithm_StaticTransformation::_internal_translation_vector() const {
  return translation_vector_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Algorithm_StaticTransformation::translation_vector() const {
  // @@protoc_insertion_point(field_list:blickfeld.protocol.config.Algorithm.StaticTransformation.translation_vector)
  return _internal_translation_vector();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Algorithm_StaticTransformation::_internal_mutable_translation_vector() {
  return &translation_vector_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Algorithm_StaticTransformation::mutable_translation_vector() {
  // @@protoc_insertion_point(field_mutable_list:blickfeld.protocol.config.Algorithm.StaticTransformation.translation_vector)
  return _internal_mutable_translation_vector();
}

// -------------------------------------------------------------------

// Algorithm

// .blickfeld.protocol.config.Algorithm.BackgroundSubtraction background_subtraction = 1;
inline bool Algorithm::_internal_has_background_subtraction() const {
  return algo_case() == kBackgroundSubtraction;
}
inline bool Algorithm::has_background_subtraction() const {
  return _internal_has_background_subtraction();
}
inline void Algorithm::set_has_background_subtraction() {
  _oneof_case_[0] = kBackgroundSubtraction;
}
inline void Algorithm::clear_background_subtraction() {
  if (_internal_has_background_subtraction()) {
    if (GetArena() == nullptr) {
      delete algo_.background_subtraction_;
    }
    clear_has_algo();
  }
}
inline ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* Algorithm::release_background_subtraction() {
  // @@protoc_insertion_point(field_release:blickfeld.protocol.config.Algorithm.background_subtraction)
  if (_internal_has_background_subtraction()) {
    clear_has_algo();
      ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* temp = algo_.background_subtraction_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    algo_.background_subtraction_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction& Algorithm::_internal_background_subtraction() const {
  return _internal_has_background_subtraction()
      ? *algo_.background_subtraction_
      : *reinterpret_cast< ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction*>(&::blickfeld::protocol::config::_Algorithm_BackgroundSubtraction_default_instance_);
}
inline const ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction& Algorithm::background_subtraction() const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.background_subtraction)
  return _internal_background_subtraction();
}
inline ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* Algorithm::unsafe_arena_release_background_subtraction() {
  // @@protoc_insertion_point(field_unsafe_arena_release:blickfeld.protocol.config.Algorithm.background_subtraction)
  if (_internal_has_background_subtraction()) {
    clear_has_algo();
    ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* temp = algo_.background_subtraction_;
    algo_.background_subtraction_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Algorithm::unsafe_arena_set_allocated_background_subtraction(::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* background_subtraction) {
  clear_algo();
  if (background_subtraction) {
    set_has_background_subtraction();
    algo_.background_subtraction_ = background_subtraction;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:blickfeld.protocol.config.Algorithm.background_subtraction)
}
inline ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* Algorithm::_internal_mutable_background_subtraction() {
  if (!_internal_has_background_subtraction()) {
    clear_algo();
    set_has_background_subtraction();
    algo_.background_subtraction_ = CreateMaybeMessage< ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction >(GetArena());
  }
  return algo_.background_subtraction_;
}
inline ::blickfeld::protocol::config::Algorithm_BackgroundSubtraction* Algorithm::mutable_background_subtraction() {
  // @@protoc_insertion_point(field_mutable:blickfeld.protocol.config.Algorithm.background_subtraction)
  return _internal_mutable_background_subtraction();
}

// .blickfeld.protocol.config.Algorithm.NeighborFilter neighbor_filter = 2;
inline bool Algorithm::_internal_has_neighbor_filter() const {
  return algo_case() == kNeighborFilter;
}
inline bool Algorithm::has_neighbor_filter() const {
  return _internal_has_neighbor_filter();
}
inline void Algorithm::set_has_neighbor_filter() {
  _oneof_case_[0] = kNeighborFilter;
}
inline void Algorithm::clear_neighbor_filter() {
  if (_internal_has_neighbor_filter()) {
    if (GetArena() == nullptr) {
      delete algo_.neighbor_filter_;
    }
    clear_has_algo();
  }
}
inline ::blickfeld::protocol::config::Algorithm_NeighborFilter* Algorithm::release_neighbor_filter() {
  // @@protoc_insertion_point(field_release:blickfeld.protocol.config.Algorithm.neighbor_filter)
  if (_internal_has_neighbor_filter()) {
    clear_has_algo();
      ::blickfeld::protocol::config::Algorithm_NeighborFilter* temp = algo_.neighbor_filter_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    algo_.neighbor_filter_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::blickfeld::protocol::config::Algorithm_NeighborFilter& Algorithm::_internal_neighbor_filter() const {
  return _internal_has_neighbor_filter()
      ? *algo_.neighbor_filter_
      : *reinterpret_cast< ::blickfeld::protocol::config::Algorithm_NeighborFilter*>(&::blickfeld::protocol::config::_Algorithm_NeighborFilter_default_instance_);
}
inline const ::blickfeld::protocol::config::Algorithm_NeighborFilter& Algorithm::neighbor_filter() const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.neighbor_filter)
  return _internal_neighbor_filter();
}
inline ::blickfeld::protocol::config::Algorithm_NeighborFilter* Algorithm::unsafe_arena_release_neighbor_filter() {
  // @@protoc_insertion_point(field_unsafe_arena_release:blickfeld.protocol.config.Algorithm.neighbor_filter)
  if (_internal_has_neighbor_filter()) {
    clear_has_algo();
    ::blickfeld::protocol::config::Algorithm_NeighborFilter* temp = algo_.neighbor_filter_;
    algo_.neighbor_filter_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Algorithm::unsafe_arena_set_allocated_neighbor_filter(::blickfeld::protocol::config::Algorithm_NeighborFilter* neighbor_filter) {
  clear_algo();
  if (neighbor_filter) {
    set_has_neighbor_filter();
    algo_.neighbor_filter_ = neighbor_filter;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:blickfeld.protocol.config.Algorithm.neighbor_filter)
}
inline ::blickfeld::protocol::config::Algorithm_NeighborFilter* Algorithm::_internal_mutable_neighbor_filter() {
  if (!_internal_has_neighbor_filter()) {
    clear_algo();
    set_has_neighbor_filter();
    algo_.neighbor_filter_ = CreateMaybeMessage< ::blickfeld::protocol::config::Algorithm_NeighborFilter >(GetArena());
  }
  return algo_.neighbor_filter_;
}
inline ::blickfeld::protocol::config::Algorithm_NeighborFilter* Algorithm::mutable_neighbor_filter() {
  // @@protoc_insertion_point(field_mutable:blickfeld.protocol.config.Algorithm.neighbor_filter)
  return _internal_mutable_neighbor_filter();
}

// .blickfeld.protocol.config.Algorithm.StaticTransformation static_transformation = 3;
inline bool Algorithm::_internal_has_static_transformation() const {
  return algo_case() == kStaticTransformation;
}
inline bool Algorithm::has_static_transformation() const {
  return _internal_has_static_transformation();
}
inline void Algorithm::set_has_static_transformation() {
  _oneof_case_[0] = kStaticTransformation;
}
inline void Algorithm::clear_static_transformation() {
  if (_internal_has_static_transformation()) {
    if (GetArena() == nullptr) {
      delete algo_.static_transformation_;
    }
    clear_has_algo();
  }
}
inline ::blickfeld::protocol::config::Algorithm_StaticTransformation* Algorithm::release_static_transformation() {
  // @@protoc_insertion_point(field_release:blickfeld.protocol.config.Algorithm.static_transformation)
  if (_internal_has_static_transformation()) {
    clear_has_algo();
      ::blickfeld::protocol::config::Algorithm_StaticTransformation* temp = algo_.static_transformation_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    algo_.static_transformation_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::blickfeld::protocol::config::Algorithm_StaticTransformation& Algorithm::_internal_static_transformation() const {
  return _internal_has_static_transformation()
      ? *algo_.static_transformation_
      : *reinterpret_cast< ::blickfeld::protocol::config::Algorithm_StaticTransformation*>(&::blickfeld::protocol::config::_Algorithm_StaticTransformation_default_instance_);
}
inline const ::blickfeld::protocol::config::Algorithm_StaticTransformation& Algorithm::static_transformation() const {
  // @@protoc_insertion_point(field_get:blickfeld.protocol.config.Algorithm.static_transformation)
  return _internal_static_transformation();
}
inline ::blickfeld::protocol::config::Algorithm_StaticTransformation* Algorithm::unsafe_arena_release_static_transformation() {
  // @@protoc_insertion_point(field_unsafe_arena_release:blickfeld.protocol.config.Algorithm.static_transformation)
  if (_internal_has_static_transformation()) {
    clear_has_algo();
    ::blickfeld::protocol::config::Algorithm_StaticTransformation* temp = algo_.static_transformation_;
    algo_.static_transformation_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Algorithm::unsafe_arena_set_allocated_static_transformation(::blickfeld::protocol::config::Algorithm_StaticTransformation* static_transformation) {
  clear_algo();
  if (static_transformation) {
    set_has_static_transformation();
    algo_.static_transformation_ = static_transformation;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:blickfeld.protocol.config.Algorithm.static_transformation)
}
inline ::blickfeld::protocol::config::Algorithm_StaticTransformation* Algorithm::_internal_mutable_static_transformation() {
  if (!_internal_has_static_transformation()) {
    clear_algo();
    set_has_static_transformation();
    algo_.static_transformation_ = CreateMaybeMessage< ::blickfeld::protocol::config::Algorithm_StaticTransformation >(GetArena());
  }
  return algo_.static_transformation_;
}
inline ::blickfeld::protocol::config::Algorithm_StaticTransformation* Algorithm::mutable_static_transformation() {
  // @@protoc_insertion_point(field_mutable:blickfeld.protocol.config.Algorithm.static_transformation)
  return _internal_mutable_static_transformation();
}

inline bool Algorithm::has_algo() const {
  return algo_case() != ALGO_NOT_SET;
}
inline void Algorithm::clear_has_algo() {
  _oneof_case_[0] = ALGO_NOT_SET;
}
inline Algorithm::AlgoCase Algorithm::algo_case() const {
  return Algorithm::AlgoCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace config
}  // namespace protocol
}  // namespace blickfeld

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_blickfeld_2fconfig_2falgorithm_2eproto
